---
apiVersion: batch/v1
kind: Job
metadata: 
  name: hellojob
spc:
  backofflimit: 5
  template:
    metadata:
      name: jobpod
    spc:
      restartPolicy: OnFailure
      containers:
        - name: alpine
          image: alpine
          command:
            - sleep
            - 10s