---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
   purpose: understanding
   concept: setbased
   env: production
spec:
  minReadySeconds: 3
  replicas: 7
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
      - key: env
        operator: NotIn
        values:
          - pro
          - cat
      - key: failing
        operator: Exists
        values:
          - dev 
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        env: dev
    spec:
      containers:
        - name: sravani
          image: nginx
          ports:
            - containerPort: 80