---
apiVersion: v1
kind: ReplicaSet
metadata: 
  name: httpd-rs-faulty
  labels:
    app: httpd
spec: 
  minReadySeconds: 6
  replicas: 3
  selector:
    matchLabels: 
      app: httpd
  template:
    metadata: 
      name: httpd
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports: 
            - containerPort: 80
          args:
            - sleep
            - 10s
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            terminationGracePeriodSeconds: 1
            timeoutSeconds: 1
            exec:
              command:
                - sleep
                - 10s
            grpc: 
              port: 80
          readinessProbe: 
            failureThreshold: 2
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            terminationGracePeriodSeconds: 1
            timeoutSeconds: 1
            exec: 
              command: 
                - sleep
                - 10s
            grpc: 
              port: 80