---
apiVersion: v1
kind: ReplicaSet
metadata: 
  name: setbased
  labels:
    app: nginx
    purpose: understanding
    concept: setbased
spec: 
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      labels:
        app: nginx
        env: dev
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
          - web
      - key: env
        operator: NotIn
        values:
          - nop
          - spc
      - key: failing
        operator: DoesNotExist
        values: 
  template:
    metadata: 
      name: nginx
      labels:
        app: nginx
        env: dev
    spec: 
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80      