---
apiVersion: v1
kind: Service
metadata: 
  name: nginx
  labels: 
    app: nginx
spec:
  selector: 
    app: nginx
  ports: 
    - name: nginx
      port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-rs
  labels: 
    app: nginx
spec: 
  minReadySeconds: 2
  replicas: 4
  selector: 
    matchLabels: 
      apps: nginx-pod
  template: 
    metadata: 
      name: nginx-pod
    spec: 
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Always
          livenessProbe: 
            failureThreshold: 1
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            terminationGracePeriodSeconds: 1
            timeoutSeconds: 1
            httpGet:
              path: /
              port: 80
          readinessProbe: 
            failureThreshold: 1
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /
              port: 80
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP
      initContainers: 
        - name: nginx1
          image: nginx
          imagePullPolicy: Always
          resources: 
            requests: 
              memory: "180Mi"
              cpu: "350Mi"
            limits:
              memory: "190Mi"
              cpu: "390Mi"
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP