---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
  labels:
    app: nginx
    env: dev
spec: 
  selector: 
    app: nginx
  type: LoadBalancer
  ports: 
    - name: nginx
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-dep
  annotations:
    kubernetes.io/change-cause: "update to phpmyadmin"
spec: 
  minReadySeconds: 2
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels: 
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata: 
      name: nginx
      labels: 
        app: nginx
    spec: 
      containers:
        - name: nginx
          image: nginx
          image: httpd
          image: phpmyadmin
          imagePullPolicy: Always
          livenessProbe: 
            failureThreshold: 1
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 10
            httpGet: 
              path: /
              port: 80
          readinessProbe: 
            failureThreshold: 1
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 10
            httpGet: 
              path: /
              port: 80
          ports: 
            - containerPort: 80
              protocol: TCP
      initContainers: 
        - name: alpine
          image: alpine
          args: 
            - sleep
            - 10s
        - name: init-myservice
          image: busybox
          args: 
            - 'sh' 
            - '-c' 
            - "until nslookup nginx-svc.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done"