---
apiVersion: v1
kind: Pod
metadata:
  name: restartfailure
spec:
  restartPolicy: Onfailure
  containers:
    - name: failure
      image: alpine
      args:
        - sleep
        - 3SM
---
apiVersion: v1
kind: Pod
metadata:
  name: restartfailure2
spec:
  restartPolicy: Onfailure
  containers:
    - name: success
      image: alpine
      args:
        - sleep
        - 3s