FROM baseImage
LABEL key="value"
RUN command
CMD [ "executable" ]
ADD source dest
COPY source dest
WORKDIR /the/workdir/path
EXPOSE 80
ENTRYPOINT [ "executable" ]
ARG name
ARG name=defaultValue
ENV key=value
VOLUME [ "/data" ]
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "executable" ] --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "executable" ]