---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerport: 80
    - name: httpd
      image: httpd
      ports:
        - containerport: 80