---
apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: nginx-ds
  annotations:
    kubernetes.io/change-cause: "update to latest"
spec: 
  minReadySeconds: 1
  revisionHistoryLimit: 10
  selector: 
    matchLabels: 
      apps: nginx
  template:
    metadata: 
      name: nginx
      labels:
        apps: nginx
    spec: 
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80