---
apiVersion: v1
kind: Service
metadata: 
  name: httpd-svc
  labels:
    app: httpd
    purpose: understanding
spec:
  ports:
    - name: httpd
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: httpd
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicaSet
metadata:
  name: httpd-rs
  labels:
    app: httpd
spec:
  minReadySeconds: 3
  replicas: 5
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      name: httpd
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
          livenessProbe:
            failureThreshold: 1
            initialDelaySeconds: 3
            periodSeconds: 1
            successThreshold: 3
            terminationGracePeriodSeconds: 1
            timeoutSeconds: 5
            httpGet: 
              path: /
              port: 80
          readinessProbe: 
            failureThreshold: 1
            initialDelaySeconds: 3
            periodSeconds: 1
            successThreshold: 3
            terminationGracePeriodSeconds: 1
            timeoutSeconds: 5
            httpGet:
              path: /
              port: 80
