---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
  labels:
    app: nginx
    env: dev
    concept: resource
spec:
  ports: 
    - name: nginx
      port: 80
      targetPort: 80
      protocol: TCP 
  selector: 
    app: nginx
  type: ClusterIP
  clusterIP: None