---
apiVersion: v1
kind: Service
metadata: 
  name: nop-svc
  labels:
    app: nop
    env: dev
    concept: resource
spec:
  ports: 
    - name: nop
      port: 5000
      targetPort: 5000
      protocol: TCP 
  selector: 
    app: nop
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-svc
  labels:
    app: nop
    env: dev
    concept: resource
spec:
  ports: 
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP 
  selector: 
    app: mysql