---
apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    app: nginx
    purpose: production
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80